services:
  app:
    build: .
    command: python -u ./web-app/app.py
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro 
    ports:
      - 5002:5002
  ml-client:
    build: ./machine-learning-client
    volumes:
      - .:/machine-learning-client
