services:
  app:
    build: ./web-app
    command: python ./web-app/app.py
    # command: python -u ./web-app/app.py
    ports:
      - "3000:3000"
    volumes:
      - .:/web-app
    links:
      - db
    container_name: app
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=animal_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js
    ports:
      - "27017:27017"
  ml-client:
    build: ./machine-learning-client
    volumes:
      - .:/machine-learning-client
    ports:
      - "3001:3000"
    container_name: ml-client
